remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Sukma's Profile]
description: [This is my profile page]
show_downloads: [false]
google_analytics: [G-LLVVZEFLQZ]